version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  mysql:
    container_name: ${NAMESPACE}_db
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-tier
  php:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - app-tier